#!/usr/bin/env bash

echo "🚀 Clearing Laravel caches..."

# Ако използваш Sail
./vendor/bin/sail artisan route:clear
./vendor/bin/sail artisan view:clear
./vendor/bin/sail artisan config:clear
./vendor/bin/sail artisan cache:clear

echo "✅ All caches cleared!"
